<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prices')->insert([
            // Терапия
            [
                'service_code' => 'В01.065.001',
                'service_name' => 'Первичная консультация врача-терапевта',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.003.004.002',
                'service_name' => 'Анестезия',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.003.004.002',
                'service_name' => 'Аппликационная анестезия',
                'price' => 200,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.012.001',
                'service_name' => 'Рентгенография',
                'price' => 400,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.012.002',
                'service_name' => 'Ортопатномограмма',
                'price' => 1000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A06.07.013',
                'service_name' => 'Компьютерная томография челюстно-лицевой области',
                'price' => 2500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.031.001',
                'service_name' => 'Постановка стекловолоконного штифта',
                'price' => 1800,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.025',
                'service_name' => 'Восстановление культи зуба под коронку до 50%',
                'price' => 1700,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.026',
                'service_name' => 'Восстановление культи зуба под коронку более 50%',
                'price' => 3500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.031.002',
                'service_name' => 'Постановка анкерного штифта',
                'price' => 800,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.031.003',
                'service_name' => 'Постановка парапульпарного штифта',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.082.001',
                'service_name' => 'Распломбировка корневого канала, запломбированного пастой',
                'price' => 1000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.082.001',
                'service_name' => 'Распломбировка корневого канала, запломбированного резорцинформалиновой пастой, цементом',
                'price' => 2000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.007.094.001',
                'service_name' => 'Извлечение инородного тела',
                'price' => 1000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030.003',
                'service_name' => 'Временная пломбировка канала гидроокисью кальция',
                'price' => 700,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030.004',
                'service_name' => 'Временная пломбировка канала метапексом',
                'price' => 1000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А11.07.027',
                'service_name' => 'Применение девитализирующей пасты',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030.002',
                'service_name' => 'Применение пасты «Пульпотек»',
                'price' => 800,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.008.003',
                'service_name' => 'Закрытие перфорационного отверстия',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A16.07.030.001',
                'service_name' => 'Инструментальная диагностика корневых каналов зуба',
                'price' => 2500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.009',
                'service_name' => 'Наложение временной пломбы',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей, однокоренной зуб',
                'price' => 2500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей, двухкоренной зуб',
                'price' => 4000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей, трехкоренной зуб',
                'price' => 5000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей, четырехкоренной и более',
                'price' => 6000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.019',
                'service_name' => 'Применение изолирующей прокладки SDR',
                'price' => 700,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.025.001',
                'service_name' => 'Полировка, шлифовка одного зуба',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.010',
                'service_name' => 'Реставрация зуба',
                'price' => 8000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.020',
                'service_name' => 'Пломба из композита светового отверждения 1 поверхность',
                'price' => 4000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.022',
                'service_name' => 'Пломба из композита светового отверждения 2 поверхности',
                'price' => 5000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.023',
                'service_name' => 'Пломба из композита светового отверждения 3 поверхности',
                'price' => 5500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.003',
                'service_name' => 'Пломба светового отверждения на фронтальную группу зубов',
                'price' => 6000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.020.001',
                'service_name' => 'Профессиональная гигиена (один зуб)',
                'price' => 250,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.001',
                'service_name' => 'Полный комплекс мероприятий профессиональной гигиены (удаление над- и поддесневого камня ультразвуком, шлифовка, полировка, air flo) 2 зубных ряда легкой степени',
                'price' => 3500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.002',
                'service_name' => 'Полный комплекс мероприятий профессиональной гигиены (удаление над- и поддесневого камня ультразвуком, шлифовка, полировка, air flo) 2 зубных ряда средней степени',
                'price' => 4000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.003',
                'service_name' => 'Полный комплекс мероприятий профессиональной гигиены (удаление над- и поддесневого камня ультразвуком, шлифовка, полировка, air flo) 2 зубных ряда сложной степени',
                'price' => 4500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.004',
                'service_name' => 'Обработка зуба бифлюоридом',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.050.001',
                'service_name' => 'Отбеливание один зуб',
                'price' => 2000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.050.002',
                'service_name' => 'Процедура комплексного отбеливания (Amazing)',
                'price' => 15000,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.050.003',
                'service_name' => 'Внутриканальное отбеливание 1 зуб (одно посещение)',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.005.010',
                'service_name' => 'Фиксация коронки',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.053.006',
                'service_name' => 'Снятие штампованной коронки',
                'price' => 500,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.053.006',
                'service_name' => 'Снятие цельнолитой или керамической коронки',
                'price' => 800,
                'unit' => 'Терапия',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ортопедия
            [
                'service_code' => 'В01.066.001',
                'service_name' => 'Первичная консультация',
                'price' => 500,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.003.004.002',
                'service_name' => 'Анестезия',
                'price' => 500,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А02.07.010.002',
                'service_name' => 'Оттиск силиконовой массой для изготовления металлокерамического, цельнолитого протеза',
                'price' => 1000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.005',
                'service_name' => 'Коронка металлокерамическая, промежуточная часть металлокерамического мостовидного протеза',
                'price' => 11000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.033.002',
                'service_name' => 'Цельнолитая корневая вкладка',
                'price' => 3000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.007',
                'service_name' => 'Коронка пластмассовая временная, изготовленная в лаборатории',
                'price' => 3000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.001',
                'service_name' => 'Коронка пластмассовая временная, изготовленная непосредственно в полости рта',
                'price' => 1000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.005.010',
                'service_name' => 'Фиксация коронки',
                'price' => 500,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.035.010',
                'service_name' => 'Съемный пластиночный протез',
                'price' => 17000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.035.002',
                'service_name' => 'Иммедиат протез',
                'price' => 3000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.036.001',
                'service_name' => 'Бюгельный протез с замковым креплением',
                'price' => 50000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.036.002',
                'service_name' => 'Бюгельный протез на опорно-удерживающих кламмерах',
                'price' => 30000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А23.07.002.037',
                'service_name' => 'Починка протеза (два элемента)',
                'price' => 3000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.023.003',
                'service_name' => 'Коррекция, перебазировка съемного протеза',
                'price' => 2000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.004',
                'service_name' => 'Коронка металлокерамическая на импланте NDI (Германия)',
                'price' => 18000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.003',
                'service_name' => 'Коронка металлокерамическая на импланте BICON (США)',
                'price' => 23000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.007',
                'service_name' => 'Коронка из диоксида циркония (полная анатомия)',
                'price' => 14000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.008',
                'service_name' => 'Коронка на диоксиде циркония с нанесением керамической массы (Е-max)',
                'price' => 18000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.002',
                'service_name' => 'Коронка из диоксида циркония (полная анатомия) на импланте NDI (Германия)',
                'price' => 21000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.001',
                'service_name' => 'Коронка на диоксиде циркония с нанесением керамической массы (Е-max) на импланте NDI (Германия)',
                'price' => 23000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.002',
                'service_name' => 'Коронка из диоксида циркония (полная анатомия) на импланте BICON (США)',
                'price' => 24000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.010',
                'service_name' => 'Коронка на диоксиде циркония с нанесением керамической массы (e-max) на импланте BICON (США)',
                'price' => 26000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.003.001',
                'service_name' => 'Виниры',
                'price' => 18000,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.053.006',
                'service_name' => 'Снятие штампованной коронки',
                'price' => 500,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.053.006',
                'service_name' => 'Снятие цельнолитой или керамической коронки',
                'price' => 800,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.094',
                'service_name' => 'Извлечение культевой вкладки',
                'price' => 500,
                'unit' => 'Ортопедия',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Хирургия
            [
                'service_code' => 'В01.067.002',
                'service_name' => 'Первичная консультация врача-хирурга',
                'price' => 500,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.003.004.002',
                'service_name' => 'Анестезия',
                'price' => 500,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.001.002',
                'service_name' => 'Удаление зуба (простое)',
                'price' => 2000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.001.004',
                'service_name' => 'Удаление зуба мудрости',
                'price' => 3000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.024',
                'service_name' => 'Удаление ретинированного или дистопированного зуба',
                'price' => 6000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.042',
                'service_name' => 'Пластика уздечки верхней губы',
                'price' => 4000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.043',
                'service_name' => 'Пластика уздечки нижней губы',
                'price' => 4000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.059',
                'service_name' => 'Гемисекция',
                'price' => 2000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.055.002',
                'service_name' => 'Синус лифтинг открытый (поднятие дна гайморовой пазухи)',
                'price' => 25000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.055.001',
                'service_name' => 'Синус лифтинг закрытый (с материалом)',
                'price' => 6000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.007',
                'service_name' => 'Резекция верхушки корня (без материала)',
                'price' => 3000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.054.001',
                'service_name' => 'Имплантация имплантами NDI (Германия)',
                'price' => 30000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.054.002',
                'service_name' => 'Имплантация имплантами BICON (США)',
                'price' => 40000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.054.003',
                'service_name' => 'Формирователь десны для имплантов NDI (Германия)',
                'price' => 2500,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.054.004',
                'service_name' => 'Формирователя десны для имплантов BICON (США)',
                'price' => 3500,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.040.003',
                'service_name' => 'Закрытие рецессии одного зуба 1-й этап',
                'price' => 5000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А 16.07.040.003',
                'service_name' => 'Закрытие рецессии одного зуба 2-й этап',
                'price' => 4000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.011.002',
                'service_name' => 'Периостотомия с дренированием',
                'price' => 2000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.055.017',
                'service_name' => 'Операция расщепления альвеолярного отростка',
                'price' => 5000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'Материалы к манипуляции А16.07.055.017',
                'service_name' => 'Использование мембраны для костной пластики, мембрана 1,5*1,5',
                'price' => 4000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'Материалы к манипуляции А16.07.055.017',
                'service_name' => 'Использование мембраны для костной пластики, мембрана 1,5*2,5',
                'price' => 6000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'Материалы к манипуляции А16.07.055.017',
                'service_name' => 'Использование остеопластического материала для замещения дефектов костной ткани',
                'price' => 4000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.040.002',
                'service_name' => 'Лоскутная операция (1 зуб)',
                'price' => 2000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.096.001',
                'service_name' => 'Пластика соустья верхнечелюстной пазухи (без материала)',
                'price' => 4000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.012.001',
                'service_name' => 'Рентгенография',
                'price' => 400,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.012.002',
                'service_name' => 'Ортопатномограмма',
                'price' => 1000,
                'unit' => 'Хирургия',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ренгенология
            [
                'service_code' => 'А06.07.012.001',
                'service_name' => 'Рентгенография',
                'price' => 400,
                'unit' => 'Ренгенология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.012.002',
                'service_name' => 'Ортопантомограмма',
                'price' => 1000,
                'unit' => 'Ренгенология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.013',
                'service_name' => 'Компьютерная томография челюстно-лицевой области',
                'price' => 2500,
                'unit' => 'Ренгенология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.013.001',
                'service_name' => 'Компьютерная томография одной области',
                'price' => 1500,
                'unit' => 'Ренгенология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А06.07.013.001',
                'service_name' => 'Компьютерная томография одной области',
                'price' => 800,
                'unit' => 'Ренгенология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
