<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PriceSeederTerapy extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prices')->insert([

            [
                'service_code' => 'В01.065.001',
                'service_name' => 'Первичный осмотр врача-стоматолога-терапевта',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.003.004.001',
                'service_name' => 'Анестезия',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.003.004.002',
                'service_name' => 'Аппликационная анестезия',
                'price' => 200,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.053',
                'service_name' => 'Снятие несьемной ортопедической конструкции (одна единица)',
                'price' => 800,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А11.07.028',
                'service_name' => 'Наложение Коффердам/OptraGate',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А17.07.003',
                'service_name' => 'Диатермокоогуляция',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.031.001',
                'service_name' => 'Постановка стекловолоконного штифта',
                'price' => 2000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.031.002',
                'service_name' => 'Постановка анкерного штифта',
                'price' => 1000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.031.003',
                'service_name' => 'Постановка парапульпарного штифта',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.082.001',
                'service_name' => 'Распломбировка корневого канала ранее леченного пастой',
                'price' => 1500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.082.002',
                'service_name' => 'Распломбировка корневого канала, ранее леченного фосфат-цементом/резорцин-формальдегидным методом',
                'price' => 2500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.007.094',
                'service_name' => 'Удаление внутриканального штифта/вкладки/ инородного тела',
                'price' => 1500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.007.030.003',
                'service_name' => 'Временная пломбировка канала гидроокисью кальция',
                'price' => 700,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030.004',
                'service_name' => 'Временная пломбировка канала пастой «метапекс»',
                'price' => 1000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А11.07.027.001',
                'service_name' => 'Наложение девитализирующей пасты',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.027.002',
                'service_name' => 'Наложение пасты «Пульпотек»',
                'price' => 1000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.008.003',
                'service_name' => 'Закрытие перфорации стенки корневого канала (МТА)',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030',
                'service_name' => 'Инструментальная диагностика корневых каналов',
                'price' => 2500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030.001',
                'service_name' => 'Инструментальная и медикоментозная обработка хорошо проходимого корневого канала',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.030.002',
                'service_name' => 'Инструментальная и медикоментозная обработка плохо проходимого канала',
                'price' => 1000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.009',
                'service_name' => 'Наложение временной пломбы',
                'price' => 800,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей (однокорневой зуб)',
                'price' => 3500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'service_code' => 'А16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей (двухкорневой зуб)',
                'price' => 5000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей (трёхкорневой зуб)',
                'price' => 6000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.008.002',
                'service_name' => 'Пломбирование корневого канала гуттаперчей (четырёхкорневой зуб)',
                'price' => 7000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.019',
                'service_name' => 'Наложение жидкотекучего композита ESTELITE UNIVERSAL FLOW/SDR',
                'price' => 1000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.010',
                'service_name' => 'Реставрация зуба композитом',
                'price' => 9000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.011',
                'service_name' => 'Восстановление зуба пломбой из фотополимера на фронтальную группу зубов',
                'price' => 8000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.012',
                'service_name' => 'Восстановление зуба пломбой из фотополимера — одна поверхность',
                'price' => 5000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.013',
                'service_name' => 'Восстановление зуба пломбой из фотополимера — две поверхности',
                'price' => 6000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.014',
                'service_name' => 'Восстановление зуба пломбой из фотополимера — три поверхности',
                'price' => 7000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.025',
                'service_name' => 'Восстановление культи зуба под коронку менее 50%',
                'price' => 2000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.002.026',
                'service_name' => 'Восстановление культи зуба под коронку более 50%',
                'price' => 4000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.001',
                'service_name' => 'Полный комплекс мероприятий профессиональной гигиены (удаление над- и поддесневого камня ультразвуком, шлифовка, полировка) — два зубных ряда лёгкой степени',
                'price' => 4000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.002',
                'service_name' => 'Полный комплекс мероприятий профессиональной гигиены — два зубных ряда средней степени',
                'price' => 4500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.003',
                'service_name' => 'Полный комплекс мероприятий профессиональной гигиены — два зубных ряда сложной степени',
                'price' => 5000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.051.004',
                'service_name' => 'Профессиональная гигиена зубов (одна единица)',
                'price' => 250,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.050.001',
                'service_name' => 'Профессиональное комплексное отбеливание зубов (Amazing)',
                'price' => 15000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.050.002',
                'service_name' => 'Профессиональное отбеливание зубов (одна единица)',
                'price' => 2000,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.050.003',
                'service_name' => 'Внутриканальное отбеливание (одна единица, одно посещение)',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.024.001',
                'service_name' => 'Местное применение реминерализующих препаратов в области одного зуба (бифлюорид)',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.003',
                'service_name' => 'Наложение лечебной повязки при заболеваниях слизистой оболочки полости рта и пародонта в области одной челюсти',
                'price' => 200,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.025.002',
                'service_name' => 'Избирательное полирование зуба',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => '16.07.049',
                'service_name' => 'Повторная фиксация коронки на постоянный цемент',
                'price' => 500,
                'section' => 'Стоматология терапевтическая',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
